### PR TITLE
Added react with signed commit with right semantics

### PR DESCRIPTION
**Pull request by ufoBeliever**
Added react with signed commit with right semantics

Issue https://github.com/igorizviekov/mt-booking_app/issues/1

### CODE REVIEW

**Review by igorizviekov — COMMENTED** [review]
please add to the description of PR which task it is closing f.e. `closes #1 `

**Comment by ufoBeliever** [comment]
> please add to the description of PR which task it is closing f.e. `closes #1 `

done

**Comment by igorizviekov** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> > please add to the description of PR which task it is closing f.e. `closes #1 `
> 
> 
> 
> done

No it's not done. The task was to update the description, not title 😉

**Comment by igorizviekov** [comment]
So now add descriptive title to your pr plus as well as a description with link to an issue

**Pull request merged**
